---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: spack
  labels:
    app: registry
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 443
    targetPort: https
  selector:
    app: registry
